"""Generate the files the C++ port reads: reference.csv, edge.csv and ig_table.h.

reference.csv   one row per real SPX option: s, mu, x_ref, clipped. x_ref is the analytic-seed
                solve with 40 Newton steps, so it checks that the C++ port reproduces the Python
                module (port fidelity). It is not independent truth: it shares ig_survival's
                precision floor. Accuracy against truth is in test_ig_quantile.py (mpmath).
                `clipped` marks rows pinned at p = 1 - 1e-14 (deep ITM quotes at or below intrinsic).
edge.csv        synthetic rows (mu < 1 and mu > e^17, both off-table; s ~ 1e-14, the clip, inside it) with x_ref
                solved in 50-digit mpmath, so the fallback path is measured against truth. Rows are
                not filtered for convergence: the large-mu block is where the double-precision
                answer is worst, and dropping it would hide that.
ig_table.h      the ln x seed table from ig_quantile._table(), so Python and C++ interpolate
                identical nodes. test_ig_quantile.py fails if the file on disk is stale.

Run from this folder: python gen_reference.py
"""

import warnings
from pathlib import Path

import numpy as np

import ig_quantile as q
import mp_truth

HERE = Path(__file__).resolve().parent
DATA_DIR = HERE.parents[1] / "fim500project" / "SPXIV-Surface" / "data"
EDGE_ROWS_PER_BLOCK = 100


def write_reference():
    price, spot, strike, t, rate, dividend = q._load_real_inputs(DATA_DIR)
    s, mu = q.survival_inputs(price, spot, strike, t, rate, dividend)
    keep = np.isfinite(mu)  # drop rows exactly at the forward (the closed form handles them)
    s, mu = s[keep], mu[keep]
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        x_ref = q.ig_quantile_survival(s, mu, n_iter=40, seed="analytic", halley=False)
    clipped = (s < 1.0001e-14).astype(int)
    out = np.column_stack([s, mu, x_ref, clipped])
    np.savetxt(HERE / "reference.csv", out, delimiter=",", header="s,mu,x_ref,clipped", comments="", fmt=["%.17g"] * 3 + ["%d"])
    print(f"reference.csv: {len(s):,} rows, {clipped.sum():,} clipped")


def write_edge():
    rng = np.random.default_rng(0)
    n = EDGE_ROWS_PER_BLOCK
    mu = np.concatenate([rng.uniform(0.3, 0.99, n), 10 ** rng.uniform(7.5, 9, n), 10 ** rng.uniform(0.5, 4, n)])
    s = np.concatenate([10 ** rng.uniform(-12, -3, n), 10 ** rng.uniform(-12, -3, n), 10 ** rng.uniform(-14.3, -13.5, n)])
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        x_double = q.ig_quantile_survival(s, mu)
    x_ref = np.array([float(mp_truth.quantile(si, mi, xi)) for si, mi, xi in zip(s, mu, x_double)])
    out = np.column_stack([s, mu, x_ref, np.zeros(len(s), dtype=int)])
    np.savetxt(HERE / "edge.csv", out, delimiter=",", header="s,mu,x_ref,clipped", comments="", fmt=["%.17g"] * 3 + ["%d"])
    print(f"edge.csv: {len(s)} rows, references from mpmath")


def table_header_text():
    table = q._table()
    rows = ",\n".join("    {" + ", ".join(f"{v:.17g}" for v in row) + "}" for row in table)
    return (
        "// Generated by gen_reference.py from ig_quantile._table(). Do not edit.\n"
        "#pragma once\n"
        f"constexpr double kTableU0 = {q.TABLE_U[0]!r}, kTableU1 = {q.TABLE_U[1]!r};  // ln mu\n"
        f"constexpr double kTableW0 = {q.TABLE_W[0]!r}, kTableW1 = {q.TABLE_W[1]!r};  // ln s\n"
        f"constexpr double kTableHu = {q.TABLE_HU!r}, kTableHw = {q.TABLE_HW!r};\n"
        f"constexpr int kTableNu = {table.shape[0]}, kTableNw = {table.shape[1]};\n"
        "// Row i, column j holds ln x at ln mu = U0 - Hu + Hu*i, ln s = W0 - Hw + Hw*j (one padding node each side).\n"
        f"constexpr double kTable[{table.shape[0]}][{table.shape[1]}] = {{\n{rows}\n}};\n"
    )


def write_table():
    text = table_header_text()
    (HERE / "ig_table.h").write_text(text)
    table = q._table()
    print(f"ig_table.h: {table.shape[0]} x {table.shape[1]} nodes")


if __name__ == "__main__":
    write_reference()
    write_edge()
    write_table()
