// Inverse-Gaussian quantile for Schadner's explicit implied-volatility formula.
// C++ port of ig_quantile.py (the reference; read its docstring for the derivation).
//
// Solves S_IG(x; mu, 1) = s for x, with s = 1 - p, by one Halley step in y = ln x on ln S(e^y) - ln s.
// Seed: a 4x4 Lagrange cubic through the ln x table in ig_table.h (generated by gen_reference.py).
// Rows outside the table's domain take an analytic seed and more steps.
#pragma once

#include <algorithm>
#include <array>
#include <cmath>

#include "ig_table.h"

namespace ig {

// Weights of the 4-point Lagrange cubic through nodes -1, 0, 1, 2 at offset t in [0, 1).
inline std::array<double, 4> lagrange_weights(double t) {
    return {-t * (t - 1) * (t - 2) / 6, (t + 1) * (t - 1) * (t - 2) / 2, -(t + 1) * t * (t - 2) / 2,
            (t + 1) * t * (t - 1) / 6};
}

constexpr double kSqrt2 = 1.4142135623730951;
constexpr double kSqrt2Pi = 2.5066282746310002;

// exp_2_over_mu = exp(2 / mu), passed in because it is constant across Newton steps.
inline double survival(double x, double mu, double exp_2_over_mu) {
    const double a = std::sqrt(x) / mu, b = 1.0 / std::sqrt(x);
    return 0.5 * std::erfc((a - b) / kSqrt2) - exp_2_over_mu * 0.5 * std::erfc((a + b) / kSqrt2);
}

inline double survival(double x, double mu) { return survival(x, mu, std::exp(2.0 / mu)); }

inline double pdf(double x, double mu) {
    return std::exp(-(x - mu) * (x - mu) / (2.0 * mu * mu * x)) / (kSqrt2Pi * x * std::sqrt(x));
}

// Phi^-1(q), q in (0, 1). Only the analytic-seed fallback uses it, so it favours obvious
// correctness over speed: Newton on ln Phi(z) - ln q, which keeps relative accuracy for tiny q.
inline double ndtri(double q) {
    if (q > 0.5) return -ndtri(1.0 - q);
    if (q == 0.5) return 0.0;
    double z = -std::sqrt(-2.0 * std::log(q));
    for (int i = 0; i < 12; ++i) {
        const double cdf = 0.5 * std::erfc(-z / kSqrt2);
        const double density = std::exp(-0.5 * z * z) / kSqrt2Pi;
        const double step = (std::log(cdf) - std::log(q)) * cdf / density;
        if (!std::isfinite(step)) break;
        z -= step;
    }
    return z;
}

// min(mu -> inf limit, Gaussian-tail limit), as in ig_seed in the Python module.
inline double analytic_seed(double s, double mu) {
    const double z0 = ndtri(0.5 + 0.5 * s);
    const double x_inf = 1.0 / (z0 * z0);
    const double z = -ndtri(s);
    const double r = 0.5 * (z * mu + std::sqrt(z * z * mu * mu + 4.0 * mu));
    return std::min(x_inf, r * r);
}

// The generated table has cells + 3 nodes per axis: cells + 1 spanning the domain plus one
// padding node each side. These fail the build if ig_table.h and its constants disagree.
constexpr int kCellsU = static_cast<int>((kTableU1 - kTableU0) / kTableHu + 0.5);
constexpr int kCellsW = static_cast<int>((kTableW1 - kTableW0) / kTableHw + 0.5);
static_assert(kTableNu == kCellsU + 3, "ig_table.h row count does not match its ln mu domain");
static_assert(kTableNw == kCellsW + 3, "ig_table.h column count does not match its ln s domain");
static_assert(sizeof(kTable) == sizeof(double) * kTableNu * kTableNw, "kTable extents do not match kTableNu/kTableNw");

// Fractional table index of (u, w) = (ln mu, ln s).
struct TablePos {
    double fu, fw;
};

inline TablePos table_pos(double u, double w) { return {(u - kTableU0) / kTableHu, (w - kTableW0) / kTableHw}; }

// Test the domain on the fractional indices, not on u and w: the stencil reads cells i..i+3, so i
// must stay below the cell count, and (w - W0) / h can round up to exactly the cell count for a w
// just inside the domain. False for NaN.
inline bool in_table(double u, double w) {
    const TablePos p = table_pos(u, w);
    return p.fu >= 0 && p.fu < kCellsU && p.fw >= 0 && p.fw < kCellsW;
}

// ln x seed. Caller must check in_table(u, w) first.
inline double table_seed(double u, double w) {
    const TablePos p = table_pos(u, w);
    const int iu = static_cast<int>(p.fu), iw = static_cast<int>(p.fw);
    const auto wu = lagrange_weights(p.fu - iu), ww = lagrange_weights(p.fw - iw);
    double y = 0.0;
    for (int a = 0; a < 4; ++a) {
        const double* row = &kTable[iu + a][iw];
        y += wu[a] * (ww[0] * row[0] + ww[1] * row[1] + ww[2] * row[2] + ww[3] * row[3]);
    }
    return y;
}

// One Newton step on h(y) = ln S(e^y) - ln s. A non-finite step keeps y, as in the Python module.
// log_s and exp_2_over_mu are per-row constants hoisted out of the loop by the caller.
inline double newton_step(double y, double log_s, double mu, double exp_2_over_mu) {
    const double x = std::exp(y);
    const double surv = survival(x, mu, exp_2_over_mu);
    const double step = (std::log(surv) - log_s) * surv / (-x * pdf(x, mu));
    return std::isfinite(step) ? y - step : y;
}

// One Halley step on the same h(y). With g1 = dh/dy and g2 = d2h/dy2:
//   g1 = -x f / S,   g2 = g1 - x^2 f (ln f)' / S - (x f / S)^2,   dy = 2 h g1 / (2 g1^2 - h g2).
// The last term is minus (f/S)^2: d/dx(-f/S) = -f'/S - (f/S)^2.
inline double halley_step(double y, double log_s, double mu, double exp_2_over_mu) {
    const double x = std::exp(y);
    const double surv = survival(x, mu, exp_2_over_mu);
    const double f = pdf(x, mu);
    const double dlogf = -1.5 / x - (x - mu) * (x + mu) / (2.0 * mu * mu * x * x);
    const double h = std::log(surv) - log_s;
    const double g1 = -x * f / surv;
    const double g2 = g1 - x * x * f * dlogf / surv - (x * f / surv) * (x * f / surv);
    const double step = 2.0 * h * g1 / (2.0 * g1 * g1 - h * g2);
    return std::isfinite(step) ? y - step : y;
}

// x with S_IG(x; mu, 1) = s. Table-seeded rows take n_iter steps (one Halley step reaches ~4e-13
// on the real data; one Newton step ~1e-8, two ~1e-13). Rows outside the table take the analytic
// seed and fallback_iter Newton steps.
inline double quantile_survival(double s, double mu, int n_iter = 1, bool halley = true, int fallback_iter = 6) {
    const double u = std::log(mu), w = std::log(s);  // w = ln s is reused by every step
    const double exp_2_over_mu = std::exp(2.0 / mu);
    if (in_table(u, w)) {
        double y = table_seed(u, w);
        for (int i = 0; i < n_iter; ++i)
            y = halley ? halley_step(y, w, mu, exp_2_over_mu) : newton_step(y, w, mu, exp_2_over_mu);
        return std::exp(y);
    }
    double y = std::log(analytic_seed(s, mu));
    for (int i = 0; i < fallback_iter; ++i) y = newton_step(y, w, mu, exp_2_over_mu);
    return std::exp(y);
}

}  // namespace ig
